### ISSUE TITLE
Attention map for DiT-based model

### ISSUE THREAD

**Issue by xduzhangjiayu** [wooyeolBaek/attention-map#11]
Hi,
Thanks for the excellent work!
Will this project support Attention map visualization for DiT-based (SD3, FLUX...) model?

**Comment by guoqincode** [comment]
Hi, thank you for your attention! We have no plans for this at the moment, but this code should be easy to write, you just need to visualize the features in AttentionProcessor using PCA.

**Comment by wooyeolBaek** [comment]
@xduzhangjiayu
It doesn't support for DiT-based models right now, and I am planning to modify it in the next update. However, due to time constraints, I don't think I'll be able to do it for a while.

If you need to use it urgently, I recommend changing the `AttnProcessor` to `AttnProcessor2_0`, and then redefining the __call__ method of the module that uses `AttnProcessor` in DiT to override it.

**Comment by xduzhangjiayu** [comment]
@wooyeolBaek Thanks for the reply, I will try it, also look forward to your update!

**Comment by wooyeolBaek** [comment]
@xduzhangjiayu
As far as I know, since the image and text hidden states are concatenated for an attention operation, the resulting matrix can be viewed as performing self-attention and cross-attention simultaneously. The upper-left and bottom-right parts of the matrix represent self-attention, while the upper-right and bottom-left parts represent cross-attention. To obtain the attention map as used in Stable Diffusion 1, you can extract the upper-right attention map, where the image is used as the query and the text as the key.

**Comment by xduzhangjiayu** [comment]
@wooyeolBaek 
Many thanks for the advice, I have tried your method and it seems works!

**Comment by wooyeolBaek** [comment]
@xduzhangjiayu 
I'm glad it worked well! I've also added features to make it compatible with SD3 and support batch operations, and I've also refactored it for more intuitive application, so feel free to refer to it if needed.

**Comment by xduzhangjiayu** [comment]
@wooyeolBaek 
Thanks for your notice and this awesome project !

**Comment by weathon** [comment]
As far as I know, when used flash attention, the whole attention map is not computed, how can we get the attention map?
